Added new init script and user support

diff --git a/templates/init.erb b/templates/init.erb
--- a/templates/init.erb
+++ b/templates/init.erb
@@ -1,50 +1,88 @@
-#!/bin/bash
+#! /bin/sh
 ### BEGIN INIT INFO
-# Provides:          redis sentinel
-# Required-Start:    $all
-# Required-Stop:    $all
-# Default-Start:    2 3 4 5
-# Default-Stop:      0 1 6
-# Short-Description: Starts redis sentinel
-# Description:      Starts redis sentinel using start-stop-daemon
+# Provides:             redis-sentinel
+# Required-Start:       $syslog $remote_fs
+# Required-Stop:        $syslog $remote_fs
+# Should-Start:         $local_fs
+# Should-Stop:          $local_fs
+# Default-Start:        2 3 4 5
+# Default-Stop:         0 1 6
+# Short-Description:    redis-sentinel - Persistent key-value db
+# Description:          redis-sentinel - Persistent key-value db
 ### END INIT INFO
 
-# MADE BY PUPPET
-# Originall written by Mathieu Elie
 
+PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
+DAEMON=/usr/bin/redis-server
+DAEMON_ARGS= <%= scope.lookupvar('redis_sentinel::config_file') -%> --sentinel
 NAME=redis-sentinel
-BIN=/usr/bin/redis-server
-SENTINEL_PID=/tmp/redis-sentinel.pid
-CMD=$1
+DESC=redis-sentinel
 
-start() {
-        echo "Starting $NAME ..."
-        exec 2>&1 $BIN <%= scope.lookupvar('redis_sentinel::config_file') -%> --sentinel | logger -t sentinel &
-        echo $! > "${SENTINEL_PID}";
-}
+RUNDIR=/var/run/redis
+PIDFILE=$RUNDIR/redis-sentinel.pid
 
-stop() {
-        PID=`cat $SENTINEL_PID`
-        echo "Stopping $NAME ($PID) ..."
-        kill $PID
-}
+test -x $DAEMON || exit 0
 
-restart() {
-        echo "Restarting $NAME ..."
-        stop
-        start
-}
+if [ -r /etc/default/$NAME ]
+then
+        . /etc/default/$NAME
+fi
 
-case "$CMD" in
-        start)
-                start
-                ;;
-        stop)
-                stop
-                ;;
-        restart)
-                restart
-                ;;
-        *)
-                echo "Usage $0 {start|stop|restart}"
+set -e
+
+case "$1" in
+  start)
+        echo -n "Starting $DESC: "
+        mkdir -p $RUNDIR
+        touch $PIDFILE
+        chown redis:redis $RUNDIR $PIDFILE
+        chmod 755 $RUNDIR
+
+        if [ -n "$ULIMIT" ]
+        then
+                ulimit -n $ULIMIT
+        fi
+
+        if start-stop-daemon --start --quiet --umask 007 --pidfile $PIDFILE --chuid redis:redis --exec $DAEMON -- $DAEMON_ARGS
+        then
+                echo "$NAME."
+        else
+                echo "failed"
+        fi
+        ;;
+  stop)
+        echo -n "Stopping $DESC: "
+        if start-stop-daemon --stop --retry forever/TERM/1 --quiet --oknodo --pidfile $PIDFILE --exec $DAEMON
+        then
+                echo "$NAME."
+        else
+                echo "failed"
+        fi
+        rm -f $PIDFILE
+        sleep 1
+        ;;
+
+  restart|force-reload)
+        ${0} stop
+        ${0} start
+        ;;
+
+  status)
+        echo -n "$DESC is "
+        if start-stop-daemon --stop --quiet --signal 0 --name ${NAME} --pidfile ${PIDFILE}
+        then
+                echo "running"
+        else
+                echo "not running"
+                exit 1
+        fi
+        ;;
+
+  *)
+        echo "Usage: /etc/init.d/$NAME {start|stop|restart|force-reload|status}" >&2
+        exit 1
+        ;;
 esac
+
+exit 0
+
